# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/sync.yml. DO NOT EDIT.
class Galtea < Formula
  desc "Galtea CLI - terminal-native client for the Galtea AI testing & evaluation platform"
  homepage "https://galtea.ai"
  version "4.26.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.26.0/galtea_4.26.0_darwin_amd64.tar.gz"
      sha256 "98d11c1cbf8ced855789754b4a810f1ebbea35903472ab2135d604418d2c1a11"

      def install
        bin.install "galtea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.26.0/galtea_4.26.0_darwin_arm64.tar.gz"
      sha256 "0c4f568a38e220946bb5302acda8fbb580b556e729e3c430662604ace903a339"

      def install
        bin.install "galtea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.26.0/galtea_4.26.0_linux_amd64.tar.gz"
      sha256 "c8c3f138738fb5f4a9ae24c9ebd0ce3f1f029d9877ebb505fb38ba0edd548577"

      def install
        bin.install "galtea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.26.0/galtea_4.26.0_linux_arm64.tar.gz"
      sha256 "2990f374822e15bf08f80673de08591a83669298e7e22d58da61d55265c3a49f"

      def install
        bin.install "galtea"
      end
    end
  end

  test do
    system "#{bin}/galtea", "--version"
  end
end
