# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/sync.yml. DO NOT EDIT.
class Galtea < Formula
  desc "Galtea CLI - terminal-native client for the Galtea AI testing & evaluation platform"
  homepage "https://galtea.ai"
  version "4.38.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.38.0/galtea_4.38.0_darwin_amd64.tar.gz"
      sha256 "6ae70620d84157ad318e18fa69713ee808f83dc220752d70cfab466c0e477e8f"

      def install
        bin.install "galtea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.38.0/galtea_4.38.0_darwin_arm64.tar.gz"
      sha256 "ea23101d97600509daf07524bfb73082d81e0c217d911be3c98ba728354929a3"

      def install
        bin.install "galtea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.38.0/galtea_4.38.0_linux_amd64.tar.gz"
      sha256 "0b1b4fca42c9aa44446af86b617aa77808fe4399b33c08a2d730a537ce299dc5"

      def install
        bin.install "galtea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Galtea-AI/homebrew-tap/releases/download/4.38.0/galtea_4.38.0_linux_arm64.tar.gz"
      sha256 "11ddd2064c19002c7f376402a9aed166570f8ce7dc81ec4fcf3f37dcc45318d1"

      def install
        bin.install "galtea"
      end
    end
  end

  test do
    system "#{bin}/galtea", "--version"
  end
end
